---
title: "finalProject"
output:
  pdf_document: default
  html_document: default
date: "2023-04-09"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rvest)
library(dplyr)
library(readxl)
```

## 

```{r salary}
url_salary <- 'https://hoopshype.com/salaries/players/2021-2022/'
x_path <- '//*[@id="content-container"]/div/div[3]/div[2]/table'
salary_table <- url_salary %>%
  read_html() %>%
  html_element(xpath = x_path) %>%
  html_table()
```

```{r}
colnames(salary_table) <- as.character(salary_table[1,])
salary_table <- salary_table[-1,]
salary_table <- subset(salary_table, select  = -ncol(salary_table))
```

```{r}
salary_table <- subset(salary_table, select = -which(names(salary_table) == "NA"))
salary_table$`2021/22`<- gsub("\\$", "", salary_table$`2021/22`)
salary_table$`2021/22`<- gsub(",", "", salary_table$`2021/22`)
names(salary_table)[names(salary_table) == "2021/22"] <- "salary"
salary_table$salary <- as.numeric(salary_table$salary)
                                
```

```{r stats}
df.stats <- read_excel('Player_stat_data.xlsx')
head(df.stats)

position <- select(df.stats, Pos) 
df.stats <- select(df.stats, -Pos)
age <- select(df.stats, Age) 
df.stats <- select(df.stats, -Age)
tm <- select(df.stats, Tm) 
df.stats <- select(df.stats, -Tm)
```

```{r distinct player occurence}
df.stats.distinct <- df.stats %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
merged.player.data <- merge(salary_table, df.stats.distinct, by = "Player", all = FALSE)
```
## Including Plots


```{r}
plot(merged.player.data$FG, merged.player.data$salary)
abline(lm(merged.player.data$salary ~ merged.player.data$FG))
plot(merged.player.data$G, merged.player.data$salary)
hist(merged.player.data$salary, nclass = 100)
```
jon added
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
